FROM node:20-bookworm-slim AS web-builder
WORKDIR /app

# 传入构建参数
ARG VITE_APP_BASE="/"
ENV VITE_APP_BASE=${VITE_APP_BASE}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=web-builder /app/dist /app/web
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /app

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
